build-arm:
  container_name: hmi-web
  image: hypriot/rpi-node:4
  command: "/bin/bash -l -c 'npm i'"

  ports:
    - "1337:1337"

  working_dir: /app
  volumes:
    - ./:/app

  restart: always

web-arm:
  container_name: hmi-web
  image: hypriot/rpi-node:4
  command: "/bin/bash -l -c 'npm start'"

  ports:
    - "1337:1337"

  working_dir: /app
  volumes:
    - ./:/app

  restart: always

build:
  container_name: hmi-build
  image: node:4
  command: "/bin/bash -l -c 'npm i'"

  ports:
    - "1337:1337"

  working_dir: /app
  volumes:
    - ./:/app

  restart: always


web:
  container_name: hmi-web
  image: node:4
  command: "/bin/bash -l -c 'npm start'"

  ports:
    - "1337:1337"

  working_dir: /app
  volumes:
    - ./:/app

  restart: always
